version: '3'

services:
  web:
    container_name: appcostos
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - backend-data:/app/data

  mongo:
    container_name: mymongo
    image: mongo
    ports:
      - "27018:27017"

  frontend:
    container_name: frontendcostos
    restart: always
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/app
    depends_on:
      - web
    tty: true

volumes:
  backend-data:
  frontend-data:
  