version: '3'

services:
  web:
    container_name: appcostos
    restart: always
    build: .
    ports:
      - "5000:4000"
    links:
      - mongo

  mongo:
    container_name: mymongo
    image: mongo
    ports:
      - "27018:27017"
    